version: '3.8'

services:
  web:
    build: .
    command: >
      sh -c "
        while ! nc -z db 5432; do
          echo 'Waiting for database...'
          sleep 1
        done
        echo 'Database is ready!'
        python manage.py migrate &&
        python manage.py collectstatic --no-input &&
        gunicorn jinja_backend.wsgi:application --bind 0.0.0.0:8000
      "
    volumes:
      - .:/app
      - static_volume:/app/static
      - media_volume:/app/media
      - log_volume:/var/log/django
    ports:
      - "8000:8000"
    environment:
      - DEBUG=0
      - POSTGRES_DB=jinja_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=05604456
      - POSTGRES_HOST=db
    depends_on:
      - db

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=jinja_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=05604456

  nginx:
    image: nginx:1.21
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - static_volume:/app/static
      - media_volume:/app/media
    ports:
      - "80:80"
    depends_on:
      - web

volumes:
  postgres_data:
  static_volume:
  media_volume:
  log_volume:
